export const FETCH_STORIES = 'FETCH_STORIES';
export const FETCH_STORIES_SUCCESS = 'FETCH_STORIES_SUCCESS';
export const FETCH_STORIES_FAILURE = 'FETCH_STORIES_FAILURE';
export const FETCH_STORIES_IDS_SUCCESS = 'FETCH_STORIES_IDS_SUCCESS';